name: Python application

on:
  push:
   branches: [ main ]
  pull_request:
   branches: [ main ]
   
jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    #- name: Build & Push Image
    #  run: |
    #    echo "${{ secrets.DOCKERPW1 }}" | docker login -u "anji1506"  --password-stdin
    #    docker image build -t Anji6789/DockerDemo1:v1
    #   docker push Anji6789/DockerDemo1:v1
        
    - name: Docker Login
  # You may pin to the exact commit or the version.
  # uses: docker/login-action@42d299face0c5c43a0487c477f595ac9cf22f1a7
      uses: docker/login-action@v1.12.0
      with:
    # Server address of Docker registry. If not set then will default to Docker Hub
         registry: https://hub.docker.com
    # Username used to log against the Docker registry
         username: ${{ secrets.DOCKERPW }}
    # Password or personal access token used to log against the Docker registry
         password: ${{ secrets.DOCKERPW1 }}
