name: Python application

on:
  push:
   branches: [ master ]
  pull_request:
   branches: [ master ]
   
jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKERPW1 }}" | docker login -u "anji1506"  --password-Anji@12345
        docker image build -t Anji6789/DockerDemo1:v1
        docker push Anji6789/DockerDemo1:v1
